### ISSUE TITLE
F1 toggle not working? always on option avbailab

### ISSUE THREAD

**Issue by danpowpow** [layeh/barnard#23]

**Comment by bontibon** [comment]
Ensure that your terminal emulator does not have a shortcut bound to that key.

There is currently not always on option.

**Comment by danpowpow** [comment]
Thanks,
i did some googling and found that putty has various keyboard modes. switching to 'xterm R6' seems to work( ie not give me garbage input), however now i get this error white text on a red background when i press F1!:

        /usr/local/go/src/io/io.go:298 +0x100
io.ReadFull(0x46b6c6a8, 0x56d321a0, 0x56cca7b6, 0x6, 0x6, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:316 +0x64
layeh.com/gumble/gumble.(*Conn).ReadPacket(0x56ca4b70, 0x56cd78c0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/pi/.go/src/layeh.com/gumble/gumble/conn.go:46 +0x190
layeh.com/gumble/gumble.(*Client).readRoutine(0x56ce42c0)
        /home/pi/.go/src/layeh.com/gumble/gumble/client.go:234 +0x7c
created by layeh.com/gumble/gumble.DialWithDialer
        /home/pi/.go/src/layeh.com/gumble/gumble/client.go:116 +0x3f0

goroutine 9 [select]:
layeh.com/gumble/gumble.(*Client).pingRoutine(0x56ce42c0)
        /home/pi/.go/src/layeh.com/gumble/gumble/client.go:217 +0x390
created by layeh.com/gumble/gumble.DialWithDialer
        /home/pi/.go/src/layeh.com/gumble/gumble/client.go:134 +0x6cc

goroutine 12 [chan receive]:
layeh.com/gumble/gumble.func·001()
        /home/pi/.go/src/layeh.com/gumble/gumble/client.go:182 +0x64
created by layeh.com/gumble/gumble.(*Client).AudioOutgoing
        /home/pi/.go/src/layeh.com/gumble/gumble/client.go:191 +0x110
exit status 2

can you offer any insight?
thanks
dp

**Comment by bontibon** [comment]
On my linux machine, using xterm-r6 does not allow me to trigger F1. I believe you want to keep the putty terminal type as "ESC[n~". 

The backtrace that you pasted seems to be missing information; there's nothing I can glean from it.

**Comment by danpowpow** [comment]
thanks for your input
with putty on ESC[n, i get the following when typing F1 in barnard

[11~

can anyone recommend a different terminal editor?

**Comment by danpowpow** [comment]
ok i've just tried mobaxterm, and i'm getting the same problem. [11~ when in Esc[n mode and red background garbage on xterm mode. 

does anyone have F1 working on ssh remote access? if so what terminal client are you using, settings etc?

thanks
dp
